require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { exec } = require('child_process');

const app = express();
app.use(cors());
app.use(express.json({ limit: '50mb' }));

const MCP = 'http://localhost:' + (process.env.MCP_PORT || 3002);
const PORT = process.env.BACKEND_PORT || 3005;
const ENV_PATH = path.join(__dirname, '../.env');

function readEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const lines = fs.readFileSync(ENV_PATH, 'utf8').split('\n');
  const env = {};
  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const idx = trimmed.indexOf('=');
    if (idx === -1) return;
    env[trimmed.substring(0, idx).trim()] = trimmed.substring(idx + 1).trim();
  });
  return env;
}

function writeEnv(envObj) {
  const lines = ['# DeliverAI Environment Configuration', '# Auto-generated by DeliverAI Setup Manager', '# NEVER commit this file to GitHub', ''];
  Object.entries(envObj).forEach(([k, v]) => lines.push(k + '=' + v));
  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf8');
}

// Config routes
app.get('/api/config/env', (req, res) => {
  const env = readEnv();
  const safe = {};
  Object.entries(env).forEach(([k, v]) => {
    const secret = ['TOKEN','SECRET','PASSWORD','KEY'].some(s => k.includes(s));
    safe[k] = secret && v ? '••••••••' : v;
  });
  res.json({ exists: fs.existsSync(ENV_PATH), config: safe });
});

app.post('/api/config/env', (req, res) => {
  try {
    const existing = readEnv();
    const updated = { ...existing, ...req.body };
    writeEnv(updated);
    res.json({ success: true, message: '.env saved successfully' });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/config/system', (req, res) => {
  const username = os.userInfo().username;
  const gitBash = 'C:\\Users\\' + username + '\\AppData\\Local\\Programs\\Git\\bin\\bash.exe';
  const claudePath = '/c/Users/' + username + '/AppData/Roaming/npm/claude';
  const gitBashWin = gitBash;
  res.json({
    username, hostname: os.hostname(), platform: os.platform(),
    gitBash: gitBashWin, claudePath,
    gitBashExists: fs.existsSync(gitBashWin),
    claudeExists: fs.existsSync('C:/Users/' + username + '/AppData/Roaming/npm/claude')
  });
});

app.get('/api/config/test/claude', (req, res) => {
  const username = os.userInfo().username;
  const gitBash = process.env.GIT_BASH_PATH || ('C:\\Users\\' + username + '\\AppData\\Local\\Programs\\Git\\bin\\bash.exe');
  const claudePath = process.env.CLAUDE_PATH || ('/c/Users/' + username + '/AppData/Roaming/npm/claude');
  exec('"' + gitBash + '" --login -c "' + claudePath + ' --version"', { timeout: 15000 }, (err, stdout) => {
    if (err) return res.json({ success: false, message: 'Claude CLI error: ' + err.message });
    res.json({ success: true, message: stdout.trim() || 'Claude CLI found' });
  });
});

app.get('/api/config/test/github', async (req, res) => {
  const token = process.env.GITHUB_TOKEN;
  if (!token || token === 'your_github_pat_here') return res.json({ success: false, message: 'GitHub token not configured' });
  try {
    const r = await fetch('https://api.github.com/user', { headers: { 'Authorization': 'token ' + token, 'User-Agent': 'DeliverAI' } });
    const data = await r.json();
    if (data.login) res.json({ success: true, message: 'Connected as ' + data.login });
    else res.json({ success: false, message: 'Invalid token' });
  } catch(e) { res.json({ success: false, message: e.message }); }
});

app.get('/api/config/test/btp', async (req, res) => {
  const { BTP_TOKEN_URL, BTP_CLIENT_ID, BTP_CLIENT_SECRET } = process.env;
  if (!BTP_TOKEN_URL || !BTP_CLIENT_ID) return res.json({ success: false, message: 'BTP credentials not configured' });
  try {
    const r = await fetch(BTP_TOKEN_URL, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'client_credentials', client_id: BTP_CLIENT_ID, client_secret: BTP_CLIENT_SECRET }) });
    const data = await r.json();
    if (data.access_token) res.json({ success: true, message: 'BTP connected' });
    else res.json({ success: false, message: data.error_description || 'Auth failed' });
  } catch(e) { res.json({ success: false, message: e.message }); }
});

app.post('/api/setup/install', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();
  const send = msg => res.write('data: ' + JSON.stringify({ message: msg }) + '\n\n');
  const dirs = ['mcp-server', 'backend', 'frontend'];
  let idx = 0;
  const next = () => {
    if (idx >= dirs.length) { send('DONE'); res.end(); return; }
    const dir = path.join(__dirname, '..', dirs[idx]);
    send('Installing ' + dirs[idx] + '...');
    exec('cd "' + dir + '" && npm install', { timeout: 120000 }, (err) => {
      send(dirs[idx] + (err ? ' had issues' : ' ready'));
      idx++; next();
    });
  };
  next();
});

// MCP proxy
const proxy = async (url, options = {}) => fetch(url, { ...options, signal: AbortSignal.timeout(300000) });

app.get('/api/health', async (req, res) => { try { const r = await proxy(MCP + '/health'); res.json(await r.json()); } catch { res.status(503).json({ status: 'error' }); } });
app.get('/api/config', async (req, res) => { try { const r = await proxy(MCP + '/config'); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/agents', async (req, res) => { try { const r = await proxy(MCP + '/agents'); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/agents/:id', async (req, res) => { try { const r = await proxy(MCP + '/agents/' + req.params.id); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.post('/api/agents/reload', async (req, res) => { try { const r = await proxy(MCP + '/agents/reload', { method: 'POST' }); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/projects', async (req, res) => { try { const r = await proxy(MCP + '/projects'); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.post('/api/projects', async (req, res) => { try { const r = await proxy(MCP + '/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(req.body) }); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/projects/:id', async (req, res) => { try { const r = await proxy(MCP + '/projects/' + req.params.id); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.put('/api/projects/:id', async (req, res) => { try { const r = await proxy(MCP + '/projects/' + req.params.id, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(req.body) }); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/projects/:id/context', async (req, res) => { try { const r = await proxy(MCP + '/projects/' + req.params.id + '/context'); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/projects/:id/files', async (req, res) => { try { const r = await proxy(MCP + '/projects/' + req.params.id + '/files'); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.post('/api/preview', async (req, res) => { try { const r = await proxy(MCP + '/preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(req.body) }); res.json(await r.json()); } catch(e) { res.status(503).json({ error: e.message }); } });
app.get('/api/generate-stream', async (req, res) => { res.setHeader('Content-Type','text/event-stream'); res.setHeader('Cache-Control','no-cache'); res.setHeader('Connection','keep-alive'); res.setHeader('Access-Control-Allow-Origin','*'); res.flushHeaders(); const params = new URLSearchParams(req.query).toString(); try { const r = await fetch(MCP + '/generate-stream?' + params); r.body.pipe(res); } catch(e) { res.write('data: ' + JSON.stringify({type:'error',data:e.message}) + '\n\n'); res.end(); } });
app.get('/api/assistant-stream', async (req, res) => { res.setHeader('Content-Type','text/event-stream'); res.setHeader('Cache-Control','no-cache'); res.setHeader('Connection','keep-alive'); res.setHeader('Access-Control-Allow-Origin','*'); res.flushHeaders(); const params = new URLSearchParams(req.query).toString(); try { const r = await fetch(MCP + '/assistant-stream?' + params); r.body.pipe(res); } catch(e) { res.write('data: ' + JSON.stringify({type:'error',data:e.message}) + '\n\n'); res.end(); } });
app.get('/api/engines', (req, res) => { res.json({ current: process.env.AI_ENGINE || 'claude-code-cli', engines: [{ id:'claude-code-cli', name:'Claude Code CLI', available:true }] }); });


// ── Data Sync Routes ──────────────────────────────────────────────────────────
const { exec } = require('child_process');
const PROJECTS_DIR = path.join(__dirname, '../projects');
const DATA_REPO = process.env.DATA_REPO;
const DATA_TOKEN = process.env.DATA_REPO_TOKEN;
const DATA_REPO_WITH_TOKEN = DATA_REPO ? DATA_REPO.replace('https://', 'https://' + DATA_TOKEN + '@') : null;
const DATA_DIR = path.join(__dirname, '../deliverAI-data');

// Clone or pull data repo
app.post('/api/sync/pull', (req, res) => {
  if (!DATA_REPO || !DATA_TOKEN) return res.json({ success: false, message: 'Data repo not configured' });
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();
  const send = msg => res.write('data: ' + JSON.stringify({ message: msg }) + '\n\n');
  send('Starting sync from private data repo...');
  const gitBash = process.env.GIT_BASH_PATH || 'C:\\Users\\vikram.f.sharma\\AppData\\Local\\Programs\\Git\\bin\\bash.exe';
  const cmd = fs.existsSync(DATA_DIR)
    ? '"' + gitBash + '" --login -c "cd /c/Users/vikram.f.sharma/DeliverAI-repo/deliverAI-data && git pull"'
    : '"' + gitBash + '" --login -c "cd /c/Users/vikram.f.sharma/DeliverAI-repo && git clone ' + DATA_REPO_WITH_TOKEN + ' deliverAI-data"';
  exec(cmd, { timeout: 60000 }, (err, stdout, stderr) => {
    if (err) { send('Error: ' + err.message); }
    else {
      send('Sync complete');
      // Copy projects from data repo to local
      const dataProjects = path.join(DATA_DIR, 'projects');
      if (fs.existsSync(dataProjects)) {
        exec('xcopy "' + dataProjects + '" "' + PROJECTS_DIR + '" /E /I /Y', (e2) => {
          send(e2 ? 'Warning copying projects: ' + e2.message : 'Projects restored from data repo');
          send('DONE');
          res.end();
        });
      } else { send('DONE'); res.end(); }
    }
  });
});

// Push projects to data repo
app.post('/api/sync/push', (req, res) => {
  if (!DATA_REPO || !DATA_TOKEN) return res.json({ success: false, message: 'Data repo not configured' });
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();
  const send = msg => res.write('data: ' + JSON.stringify({ message: msg }) + '\n\n');
  send('Pushing data to private repo...');
  const gitBash = process.env.GIT_BASH_PATH || 'C:\\Users\\vikram.f.sharma\\AppData\\Local\\Programs\\Git\\bin\\bash.exe';
  // Clone if not exists
  if (!fs.existsSync(DATA_DIR)) {
    exec('"' + gitBash + '" --login -c "cd /c/Users/vikram.f.sharma/DeliverAI-repo && git clone ' + DATA_REPO_WITH_TOKEN + ' deliverAI-data"', { timeout: 30000 }, (err) => {
      if (err) { send('Error cloning: ' + err.message); res.end(); return; }
      doPush(gitBash, send, res);
    });
  } else { doPush(gitBash, send, res); }
});

function doPush(gitBash, send, res) {
  const PROJECTS_DIR_LOCAL = path.join(__dirname, '../projects');
  const DATA_PROJECTS = path.join(DATA_DIR, 'projects');
  // Copy projects to data repo
  exec('xcopy "' + PROJECTS_DIR_LOCAL + '" "' + DATA_PROJECTS + '" /E /I /Y', (err) => {
    if (err) send('Warning: ' + err.message);
    else send('Projects copied to data repo');
    const date = new Date().toISOString().split('T')[0];
    const username = require('os').userInfo().username;
    const cmd = '"' + gitBash + '" --login -c "cd /c/Users/vikram.f.sharma/DeliverAI-repo/deliverAI-data && git add -A && git commit -m \"Sync - ' + username + ' - ' + date + '\" && git push"';
    exec(cmd, { timeout: 60000 }, (err2, stdout) => {
      if (err2 && !err2.message.includes('nothing to commit')) {
        send('Error pushing: ' + err2.message);
      } else {
        send('Successfully synced to private repo');
      }
      send('DONE');
      res.end();
    });
  });
}

app.listen(PORT, () => {
  console.log('\n╔══════════════════════════════════════════════╗');
  console.log('║  DeliverAI Backend           :' + PORT + '          ║');
  console.log('║  MCP Server:  ' + MCP + '   ║');
  console.log('╚══════════════════════════════════════════════╝\n');
});
